version: '2.1'

services:

  rabbit:
    build: rabbit_mq/.
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - local

  dmsmongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - local

  ts-node-docker:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./api/src:/home/node/app/src
      - ./api/nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run start
    networks:
      - local
    depends_on:
      rabbit:
        condition: service_healthy

networks:
  local:


